In [ ]:
import numpy as np
import cv2
import matplotlib.pyplot as plt

img_1 = cv2.imread('PATH/ref1img.jpg')
img_2 = cv2.imread('PATH/ref7img.jpg')

color1x = [460, 410, 350, 300, 250, 200, 160, 100, 30]
color7x = [450, 390, 340, 290, 240, 170, 130, 100, 20]

for x in color1x:
  print(img_1[100, x])
print('**************')
for x in color7x:
  print(img_2[100, x])

[219  62  36]
[ 47  66 255]
[235 116 254]
[ 70 205  35]
[254 251  82]
[117 255 253]
[255 254 253]
[80 86 37]
[43 60 17]
**************
[136  92   1]
[  8  69 187]
[130 126 167]
[ 41 222   0]
[197 252   0]
[  3 253 104]
[206 255  97]
[ 64 125  21]
[17 65  0]
